/**
 * Public Domain, use as you wish
 *
 * Created by AqD on 2014/08/16.
 */
package fr.threedijnns.gl.impl;

import com.jogamp.opengl.*;

import static com.jogamp.opengl.GL4bc.*;
import static fr.threedijnns.gl.JOGL.gl;

public class GLContextCapabilities {

	protected static GLContextCapabilities instance;

	public static GLContextCapabilities get() {
		if (instance == null)
			instance = new GLContextCapabilities();
		return instance;
	}

	public final boolean OpenGL11;
	public final boolean OpenGL12;
	public final boolean OpenGL13;
	public final boolean OpenGL14;
	public final boolean OpenGL15;
	public final boolean OpenGL20;
	public final boolean OpenGL21;
	public final boolean OpenGL30;
	public final boolean OpenGL31;
	public final boolean OpenGL32;
	public final boolean OpenGL33;
	public final boolean OpenGL40;
	public final boolean OpenGL41;
	public final boolean OpenGL42;
	public final boolean OpenGL43;
	public final boolean GL_AMD_blend_minmax_factor;
	public final boolean GL_AMD_conservative_depth;
	public final boolean GL_AMD_debug_output;
	public final boolean GL_AMD_depth_clamp_separate;
	public final boolean GL_AMD_draw_buffers_blend;
	public final boolean GL_AMD_multi_draw_indirect;
	public final boolean GL_AMD_name_gen_delete;
	public final boolean GL_AMD_performance_monitor;
	public final boolean GL_AMD_pinned_memory;
	public final boolean GL_AMD_query_buffer_object;
	public final boolean GL_AMD_sample_positions;
	public final boolean GL_AMD_seamless_cubemap_per_texture;
	public final boolean GL_AMD_shader_stencil_export;
	public final boolean GL_AMD_shader_trinary_minmax;
	public final boolean GL_AMD_sparse_texture;
	public final boolean GL_AMD_stencil_operation_extended;
	public final boolean GL_AMD_texture_texture4;
	public final boolean GL_AMD_transform_feedback3_lines_triangles;
	public final boolean GL_AMD_vertex_shader_layer;
	public final boolean GL_AMD_vertex_shader_tessellator;
	public final boolean GL_AMD_vertex_shader_viewport_index;
	public final boolean GL_APPLE_aux_depth_stencil;
	public final boolean GL_APPLE_client_storage;
	public final boolean GL_APPLE_element_array;
	public final boolean GL_APPLE_fence;
	public final boolean GL_APPLE_float_pixels;
	public final boolean GL_APPLE_flush_buffer_range;
	public final boolean GL_APPLE_object_purgeable;
	public final boolean GL_APPLE_packed_pixels;
	public final boolean GL_APPLE_rgb_422;
	public final boolean GL_APPLE_row_bytes;
	public final boolean GL_APPLE_texture_range;
	public final boolean GL_APPLE_vertex_array_object;
	public final boolean GL_APPLE_vertex_array_range;
	public final boolean GL_APPLE_vertex_program_evaluators;
	public final boolean GL_APPLE_ycbcr_422;
	public final boolean GL_ARB_ES2_compatibility;
	public final boolean GL_ARB_ES3_compatibility;
	public final boolean GL_ARB_arrays_of_arrays;
	public final boolean GL_ARB_base_instance;
	public final boolean GL_ARB_blend_func_extended;
	public final boolean GL_ARB_cl_event;
	public final boolean GL_ARB_clear_buffer_object;
	public final boolean GL_ARB_color_buffer_float;
	public final boolean GL_ARB_compatibility;
	public final boolean GL_ARB_compressed_texture_pixel_storage;
	public final boolean GL_ARB_compute_shader;
	public final boolean GL_ARB_conservative_depth;
	public final boolean GL_ARB_copy_buffer;
	public final boolean GL_ARB_copy_image;
	public final boolean GL_ARB_debug_output;
	public final boolean GL_ARB_depth_buffer_float;
	public final boolean GL_ARB_depth_clamp;
	public final boolean GL_ARB_depth_texture;
	public final boolean GL_ARB_draw_buffers;
	public final boolean GL_ARB_draw_buffers_blend;
	public final boolean GL_ARB_draw_elements_base_vertex;
	public final boolean GL_ARB_draw_indirect;
	public final boolean GL_ARB_draw_instanced;
	public final boolean GL_ARB_explicit_attrib_location;
	public final boolean GL_ARB_explicit_uniform_location;
	public final boolean GL_ARB_fragment_coord_conventions;
	public final boolean GL_ARB_fragment_layer_viewport;
	public final boolean GL_ARB_fragment_program;
	public final boolean GL_ARB_fragment_program_shadow;
	public final boolean GL_ARB_fragment_shader;
	public final boolean GL_ARB_framebuffer_no_attachments;
	public final boolean GL_ARB_framebuffer_object;
	public final boolean GL_ARB_framebuffer_sRGB;
	public final boolean GL_ARB_geometry_shader4;
	public final boolean GL_ARB_get_program_binary;
	public final boolean GL_ARB_gpu_shader5;
	public final boolean GL_ARB_gpu_shader_fp64;
	public final boolean GL_ARB_half_float_pixel;
	public final boolean GL_ARB_half_float_vertex;
	public final boolean GL_ARB_imaging;
	public final boolean GL_ARB_instanced_arrays;
	public final boolean GL_ARB_internalformat_query;
	public final boolean GL_ARB_internalformat_query2;
	public final boolean GL_ARB_invalidate_subdata;
	public final boolean GL_ARB_map_buffer_alignment;
	public final boolean GL_ARB_map_buffer_range;
	public final boolean GL_ARB_matrix_palette;
	public final boolean GL_ARB_multi_draw_indirect;
	public final boolean GL_ARB_multisample;
	public final boolean GL_ARB_multitexture;
	public final boolean GL_ARB_occlusion_query;
	public final boolean GL_ARB_occlusion_query2;
	public final boolean GL_ARB_pixel_buffer_object;
	public final boolean GL_ARB_point_parameters;
	public final boolean GL_ARB_point_sprite;
	public final boolean GL_ARB_program_interface_query;
	public final boolean GL_ARB_provoking_vertex;
	public final boolean GL_ARB_robust_buffer_access_behavior;
	public final boolean GL_ARB_robustness;
	public final boolean GL_ARB_robustness_isolation;
	public final boolean GL_ARB_sample_shading;
	public final boolean GL_ARB_sampler_objects;
	public final boolean GL_ARB_seamless_cube_map;
	public final boolean GL_ARB_separate_shader_objects;
	public final boolean GL_ARB_shader_atomic_counters;
	public final boolean GL_ARB_shader_bit_encoding;
	public final boolean GL_ARB_shader_image_load_store;
	public final boolean GL_ARB_shader_image_size;
	public final boolean GL_ARB_shader_objects;
	public final boolean GL_ARB_shader_precision;
	public final boolean GL_ARB_shader_stencil_export;
	public final boolean GL_ARB_shader_storage_buffer_object;
	public final boolean GL_ARB_shader_subroutine;
	public final boolean GL_ARB_shader_texture_lod;
	public final boolean GL_ARB_shading_language_100;
	public final boolean GL_ARB_shading_language_420pack;
	public final boolean GL_ARB_shading_language_include;
	public final boolean GL_ARB_shading_language_packing;
	public final boolean GL_ARB_shadow;
	public final boolean GL_ARB_shadow_ambient;
	public final boolean GL_ARB_stencil_texturing;
	public final boolean GL_ARB_sync;
	public final boolean GL_ARB_tessellation_shader;
	public final boolean GL_ARB_texture_border_clamp;
	public final boolean GL_ARB_texture_buffer_object;
	public final boolean GL_ARB_texture_buffer_object_rgb32;
	public final boolean GL_ARB_texture_buffer_range;
	public final boolean GL_ARB_texture_compression;
	public final boolean GL_ARB_texture_compression_bptc;
	public final boolean GL_ARB_texture_compression_rgtc;
	public final boolean GL_ARB_texture_cube_map;
	public final boolean GL_ARB_texture_cube_map_array;
	public final boolean GL_ARB_texture_env_add;
	public final boolean GL_ARB_texture_env_combine;
	public final boolean GL_ARB_texture_env_crossbar;
	public final boolean GL_ARB_texture_env_dot3;
	public final boolean GL_ARB_texture_float;
	public final boolean GL_ARB_texture_gather;
	public final boolean GL_ARB_texture_mirrored_repeat;
	public final boolean GL_ARB_texture_multisample;
	public final boolean GL_ARB_texture_non_power_of_two;
	public final boolean GL_ARB_texture_query_levels;
	public final boolean GL_ARB_texture_query_lod;
	public final boolean GL_ARB_texture_rectangle;
	public final boolean GL_ARB_texture_rg;
	public final boolean GL_ARB_texture_rgb10_a2ui;
	public final boolean GL_ARB_texture_storage;
	public final boolean GL_ARB_texture_storage_multisample;
	public final boolean GL_ARB_texture_swizzle;
	public final boolean GL_ARB_texture_view;
	public final boolean GL_ARB_timer_query;
	public final boolean GL_ARB_transform_feedback2;
	public final boolean GL_ARB_transform_feedback3;
	public final boolean GL_ARB_transform_feedback_instanced;
	public final boolean GL_ARB_transpose_matrix;
	public final boolean GL_ARB_uniform_buffer_object;
	public final boolean GL_ARB_vertex_array_bgra;
	public final boolean GL_ARB_vertex_array_object;
	public final boolean GL_ARB_vertex_attrib_64bit;
	public final boolean GL_ARB_vertex_attrib_binding;
	public final boolean GL_ARB_vertex_blend;
	public final boolean GL_ARB_vertex_buffer_object;
	public final boolean GL_ARB_vertex_program;
	public final boolean GL_ARB_vertex_shader;
	public final boolean GL_ARB_vertex_type_2_10_10_10_rev;
	public final boolean GL_ARB_viewport_array;
	public final boolean GL_ARB_window_pos;
	public final boolean GL_ATI_draw_buffers;
	public final boolean GL_ATI_element_array;
	public final boolean GL_ATI_envmap_bumpmap;
	public final boolean GL_ATI_fragment_shader;
	public final boolean GL_ATI_map_object_buffer;
	public final boolean GL_ATI_meminfo;
	public final boolean GL_ATI_pn_triangles;
	public final boolean GL_ATI_separate_stencil;
	public final boolean GL_ATI_shader_texture_lod;
	public final boolean GL_ATI_text_fragment_shader;
	public final boolean GL_ATI_texture_compression_3dc;
	public final boolean GL_ATI_texture_env_combine3;
	public final boolean GL_ATI_texture_float;
	public final boolean GL_ATI_texture_mirror_once;
	public final boolean GL_ATI_vertex_array_object;
	public final boolean GL_ATI_vertex_attrib_array_object;
	public final boolean GL_ATI_vertex_streams;
	public final boolean GL_EXT_abgr;
	public final boolean GL_EXT_bgra;
	public final boolean GL_EXT_bindable_uniform;
	public final boolean GL_EXT_blend_color;
	public final boolean GL_EXT_blend_equation_separate;
	public final boolean GL_EXT_blend_func_separate;
	public final boolean GL_EXT_blend_minmax;
	public final boolean GL_EXT_blend_subtract;
	public final boolean GL_EXT_Cg_shader;
	public final boolean GL_EXT_compiled_vertex_array;
	public final boolean GL_EXT_depth_bounds_test;
	public final boolean GL_EXT_direct_state_access;
	public final boolean GL_EXT_draw_buffers2;
	public final boolean GL_EXT_draw_instanced;
	public final boolean GL_EXT_draw_range_elements;
	public final boolean GL_EXT_fog_coord;
	public final boolean GL_EXT_framebuffer_blit;
	public final boolean GL_EXT_framebuffer_multisample;
	public final boolean GL_EXT_framebuffer_multisample_blit_scaled;
	public final boolean GL_EXT_framebuffer_object;
	public final boolean GL_EXT_framebuffer_sRGB;
	public final boolean GL_EXT_geometry_shader4;
	public final boolean GL_EXT_gpu_program_parameters;
	public final boolean GL_EXT_gpu_shader4;
	public final boolean GL_EXT_multi_draw_arrays;
	public final boolean GL_EXT_packed_depth_stencil;
	public final boolean GL_EXT_packed_float;
	public final boolean GL_EXT_packed_pixels;
	public final boolean GL_EXT_paletted_texture;
	public final boolean GL_EXT_pixel_buffer_object;
	public final boolean GL_EXT_point_parameters;
	public final boolean GL_EXT_provoking_vertex;
	public final boolean GL_EXT_rescale_normal;
	public final boolean GL_EXT_secondary_color;
	public final boolean GL_EXT_separate_shader_objects;
	public final boolean GL_EXT_separate_specular_color;
	public final boolean GL_EXT_shader_image_load_store;
	public final boolean GL_EXT_shadow_funcs;
	public final boolean GL_EXT_shared_texture_palette;
	public final boolean GL_EXT_stencil_clear_tag;
	public final boolean GL_EXT_stencil_two_side;
	public final boolean GL_EXT_stencil_wrap;
	public final boolean GL_EXT_texture_3d;
	public final boolean GL_EXT_texture_array;
	public final boolean GL_EXT_texture_buffer_object;
	public final boolean GL_EXT_texture_compression_latc;
	public final boolean GL_EXT_texture_compression_rgtc;
	public final boolean GL_EXT_texture_compression_s3tc;
	public final boolean GL_EXT_texture_env_combine;
	public final boolean GL_EXT_texture_env_dot3;
	public final boolean GL_EXT_texture_edge_clamp;
	public final boolean GL_EXT_texture_filter_anisotropic;
	public final boolean GL_EXT_texture_integer;
	public final boolean GL_EXT_texture_lod_bias;
	public final boolean GL_EXT_texture_mirror_clamp;
	public final boolean GL_EXT_texture_rectangle;
	public final boolean GL_EXT_texture_sRGB;
	public final boolean GL_EXT_texture_sRGB_decode;
	public final boolean GL_EXT_texture_shared_exponent;
	public final boolean GL_EXT_texture_snorm;
	public final boolean GL_EXT_texture_swizzle;
	public final boolean GL_EXT_timer_query;
	public final boolean GL_EXT_transform_feedback;
	public final boolean GL_EXT_vertex_array_bgra;
	public final boolean GL_EXT_vertex_attrib_64bit;
	public final boolean GL_EXT_vertex_shader;
	public final boolean GL_EXT_vertex_weighting;
	public final boolean GL_GREMEDY_string_marker;
	public final boolean GL_HP_occlusion_test;
	public final boolean GL_IBM_rasterpos_clip;
	public final boolean GL_INTEL_map_texture;
	public final boolean GL_KHR_debug;
	public final boolean GL_KHR_texture_compression_astc_ldr;
	public final boolean GL_NVX_gpu_memory_info;
	public final boolean GL_NV_bindless_texture;
	public final boolean GL_NV_blend_square;
	public final boolean GL_NV_compute_program5;
	public final boolean GL_NV_conditional_render;
	public final boolean GL_NV_copy_depth_to_color;
	public final boolean GL_NV_copy_image;
	public final boolean GL_NV_deep_texture3D;
	public final boolean GL_NV_depth_buffer_float;
	public final boolean GL_NV_depth_clamp;
	public final boolean GL_NV_draw_texture;
	public final boolean GL_NV_evaluators;
	public final boolean GL_NV_explicit_multisample;
	public final boolean GL_NV_fence;
	public final boolean GL_NV_float_buffer;
	public final boolean GL_NV_fog_distance;
	public final boolean GL_NV_fragment_program;
	public final boolean GL_NV_fragment_program2;
	public final boolean GL_NV_fragment_program4;
	public final boolean GL_NV_fragment_program_option;
	public final boolean GL_NV_framebuffer_multisample_coverage;
	public final boolean GL_NV_geometry_program4;
	public final boolean GL_NV_geometry_shader4;
	public final boolean GL_NV_gpu_program4;
	public final boolean GL_NV_gpu_program5;
	public final boolean GL_NV_gpu_shader5;
	public final boolean GL_NV_half_float;
	public final boolean GL_NV_light_max_exponent;
	public final boolean GL_NV_multisample_coverage;
	public final boolean GL_NV_multisample_filter_hint;
	public final boolean GL_NV_occlusion_query;
	public final boolean GL_NV_packed_depth_stencil;
	public final boolean GL_NV_parameter_buffer_object;
	public final boolean GL_NV_parameter_buffer_object2;
	public final boolean GL_NV_path_rendering;
	public final boolean GL_NV_pixel_data_range;
	public final boolean GL_NV_point_sprite;
	public final boolean GL_NV_present_video;
	public final boolean GL_NV_primitive_restart;
	public final boolean GL_NV_register_combiners;
	public final boolean GL_NV_register_combiners2;
	public final boolean GL_NV_shader_atomic_counters;
	public final boolean GL_NV_shader_atomic_float;
	public final boolean GL_NV_shader_buffer_load;
	public final boolean GL_NV_shader_buffer_store;
	public final boolean GL_NV_shader_storage_buffer_object;
	public final boolean GL_NV_tessellation_program5;
	public final boolean GL_NV_texgen_reflection;
	public final boolean GL_NV_texture_barrier;
	public final boolean GL_NV_texture_compression_vtc;
	public final boolean GL_NV_texture_env_combine4;
	public final boolean GL_NV_texture_expand_normal;
	public final boolean GL_NV_texture_multisample;
	public final boolean GL_NV_texture_rectangle;
	public final boolean GL_NV_texture_shader;
	public final boolean GL_NV_texture_shader2;
	public final boolean GL_NV_texture_shader3;
	public final boolean GL_NV_transform_feedback;
	public final boolean GL_NV_transform_feedback2;
	public final boolean GL_NV_vertex_array_range;
	public final boolean GL_NV_vertex_array_range2;
	public final boolean GL_NV_vertex_attrib_integer_64bit;
	public final boolean GL_NV_vertex_buffer_unified_memory;
	public final boolean GL_NV_vertex_program;
	public final boolean GL_NV_vertex_program1_1;
	public final boolean GL_NV_vertex_program2;
	public final boolean GL_NV_vertex_program2_option;
	public final boolean GL_NV_vertex_program3;
	public final boolean GL_NV_vertex_program4;
	public final boolean GL_NV_video_capture;
	public final boolean GL_SGIS_generate_mipmap;
	public final boolean GL_SGIS_texture_lod;
	public final boolean GL_SUN_slice_accum;

	protected GLContextCapabilities() {
		if (gl == null)
			throw new IllegalStateException();

		String    version = gl.glGetString(GL_VERSION).substring(0, 3);
		GLProfile profile = gl.getGLProfile();

		this.OpenGL11 = true;
		this.OpenGL12 = true;
		this.OpenGL13 = true;
		this.OpenGL14 = true;
		this.OpenGL15 = true;
		this.OpenGL20 = profile.isGL2();
		this.OpenGL21 = profile.isGL3() || version.compareTo("2.1") >= 0;
		this.OpenGL30 = profile.isGL3();
		this.OpenGL31 = profile.isGL4() || version.compareTo("3.1") >= 0;
		this.OpenGL32 = profile.isGL4() || version.compareTo("3.2") >= 0;
		this.OpenGL33 = profile.isGL4() || version.compareTo("3.3") >= 0;
		this.OpenGL40 = profile.isGL4();
		this.OpenGL41 = version.compareTo("4.1") >= 0;
		this.OpenGL42 = version.compareTo("4.2") >= 0;
		this.OpenGL43 = version.compareTo("4.3") >= 0;

		this.GL_AMD_blend_minmax_factor 					= gl.isExtensionAvailable("GL_AMD_blend_minmax_factor");
		this.GL_AMD_conservative_depth 						= gl.isExtensionAvailable("GL_AMD_conservative_depth");
		this.GL_AMD_debug_output 							= gl.isExtensionAvailable("GL_AMD_debug_output");
		this.GL_AMD_depth_clamp_separate 					= gl.isExtensionAvailable("GL_AMD_depth_clamp_separate");
		this.GL_AMD_draw_buffers_blend 						= gl.isExtensionAvailable("GL_AMD_draw_buffers_blend");
		this.GL_AMD_multi_draw_indirect 					= gl.isExtensionAvailable("GL_AMD_multi_draw_indirect");
		this.GL_AMD_name_gen_delete 						= gl.isExtensionAvailable("GL_AMD_name_gen_delete");
		this.GL_AMD_performance_monitor 					= gl.isExtensionAvailable("GL_AMD_performance_monitor");
		this.GL_AMD_pinned_memory 							= gl.isExtensionAvailable("GL_AMD_pinned_memory");
		this.GL_AMD_query_buffer_object 					= gl.isExtensionAvailable("GL_AMD_query_buffer_object");
		this.GL_AMD_sample_positions 						= gl.isExtensionAvailable("GL_AMD_sample_positions");
		this.GL_AMD_seamless_cubemap_per_texture 			= gl.isExtensionAvailable("GL_AMD_seamless_cubemap_per_texture");
		this.GL_AMD_shader_stencil_export 					= gl.isExtensionAvailable("GL_AMD_shader_stencil_export");
		this.GL_AMD_shader_trinary_minmax 					= gl.isExtensionAvailable("GL_AMD_shader_trinary_minmax");
		this.GL_AMD_sparse_texture 							= gl.isExtensionAvailable("GL_AMD_sparse_texture");
		this.GL_AMD_stencil_operation_extended 				= gl.isExtensionAvailable("GL_AMD_stencil_operation_extended");
		this.GL_AMD_texture_texture4 						= gl.isExtensionAvailable("GL_AMD_texture_texture4");
		this.GL_AMD_transform_feedback3_lines_triangles 	= gl.isExtensionAvailable("GL_AMD_transform_feedback3_lines_triangles");
		this.GL_AMD_vertex_shader_layer 					= gl.isExtensionAvailable("GL_AMD_vertex_shader_layer");
		this.GL_AMD_vertex_shader_tessellator 				= gl.isExtensionAvailable("GL_AMD_vertex_shader_tessellator");
		this.GL_AMD_vertex_shader_viewport_index 			= gl.isExtensionAvailable("GL_AMD_vertex_shader_viewport_index");
		this.GL_APPLE_aux_depth_stencil 					= gl.isExtensionAvailable("GL_APPLE_aux_depth_stencil");
		this.GL_APPLE_client_storage 						= gl.isExtensionAvailable("GL_APPLE_client_storage");
		this.GL_APPLE_element_array 						= gl.isExtensionAvailable("GL_APPLE_element_array");
		this.GL_APPLE_fence 								= gl.isExtensionAvailable("GL_APPLE_fence");
		this.GL_APPLE_float_pixels 							= gl.isExtensionAvailable("GL_APPLE_float_pixels");
		this.GL_APPLE_flush_buffer_range 					= gl.isExtensionAvailable("GL_APPLE_flush_buffer_range");
		this.GL_APPLE_object_purgeable 						= gl.isExtensionAvailable("GL_APPLE_object_purgeable");
		this.GL_APPLE_packed_pixels 						= gl.isExtensionAvailable("GL_APPLE_packed_pixels");
		this.GL_APPLE_rgb_422 								= gl.isExtensionAvailable("GL_APPLE_rgb_422");
		this.GL_APPLE_row_bytes 							= gl.isExtensionAvailable("GL_APPLE_row_bytes");
		this.GL_APPLE_texture_range 						= gl.isExtensionAvailable("GL_APPLE_texture_range");
		this.GL_APPLE_vertex_array_object 					= gl.isExtensionAvailable("GL_APPLE_vertex_array_object");
		this.GL_APPLE_vertex_array_range 					= gl.isExtensionAvailable("GL_APPLE_vertex_array_range");
		this.GL_APPLE_vertex_program_evaluators 			= gl.isExtensionAvailable("GL_APPLE_vertex_program_evaluators");
		this.GL_APPLE_ycbcr_422 							= gl.isExtensionAvailable("GL_APPLE_ycbcr_422");
		this.GL_ARB_ES2_compatibility 						= gl.isExtensionAvailable("GL_ARB_ES2_compatibility");
		this.GL_ARB_ES3_compatibility 						= gl.isExtensionAvailable("GL_ARB_ES3_compatibility");
		this.GL_ARB_arrays_of_arrays 						= gl.isExtensionAvailable("GL_ARB_arrays_of_arrays");
		this.GL_ARB_base_instance 							= gl.isExtensionAvailable("GL_ARB_base_instance");
		this.GL_ARB_blend_func_extended 					= gl.isExtensionAvailable("GL_ARB_blend_func_extended");
		this.GL_ARB_cl_event 								= gl.isExtensionAvailable("GL_ARB_cl_event");
		this.GL_ARB_clear_buffer_object 					= gl.isExtensionAvailable("GL_ARB_clear_buffer_object");
		this.GL_ARB_color_buffer_float 						= gl.isExtensionAvailable("GL_ARB_color_buffer_float");
		this.GL_ARB_compatibility 							= gl.isExtensionAvailable("GL_ARB_compatibility");
		this.GL_ARB_compressed_texture_pixel_storage 		= gl.isExtensionAvailable("GL_ARB_compressed_texture_pixel_storage");
		this.GL_ARB_compute_shader 							= gl.isExtensionAvailable("GL_ARB_compute_shader");
		this.GL_ARB_conservative_depth 						= gl.isExtensionAvailable("GL_ARB_conservative_depth");
		this.GL_ARB_copy_buffer 							= gl.isExtensionAvailable("GL_ARB_copy_buffer");
		this.GL_ARB_copy_image 								= gl.isExtensionAvailable("GL_ARB_copy_image");
		this.GL_ARB_debug_output 							= gl.isExtensionAvailable("GL_ARB_debug_output");
		this.GL_ARB_depth_buffer_float 						= gl.isExtensionAvailable("GL_ARB_depth_buffer_float");
		this.GL_ARB_depth_clamp 							= gl.isExtensionAvailable("GL_ARB_depth_clamp");
		this.GL_ARB_depth_texture 							= gl.isExtensionAvailable("GL_ARB_depth_texture");
		this.GL_ARB_draw_buffers 							= gl.isExtensionAvailable("GL_ARB_draw_buffers");
		this.GL_ARB_draw_buffers_blend 						= gl.isExtensionAvailable("GL_ARB_draw_buffers_blend");
		this.GL_ARB_draw_elements_base_vertex 				= gl.isExtensionAvailable("GL_ARB_draw_elements_base_vertex");
		this.GL_ARB_draw_indirect 							= gl.isExtensionAvailable("GL_ARB_draw_indirect");
		this.GL_ARB_draw_instanced 							= gl.isExtensionAvailable("GL_ARB_draw_instanced");
		this.GL_ARB_explicit_attrib_location 				= gl.isExtensionAvailable("GL_ARB_explicit_attrib_location");
		this.GL_ARB_explicit_uniform_location 				= gl.isExtensionAvailable("GL_ARB_explicit_uniform_location");
		this.GL_ARB_fragment_coord_conventions 				= gl.isExtensionAvailable("GL_ARB_fragment_coord_conventions");
		this.GL_ARB_fragment_layer_viewport 				= gl.isExtensionAvailable("GL_ARB_fragment_layer_viewport");
		this.GL_ARB_fragment_program 						= gl.isExtensionAvailable("GL_ARB_fragment_program");
		this.GL_ARB_fragment_program_shadow 				= gl.isExtensionAvailable("GL_ARB_fragment_program_shadow");
		this.GL_ARB_fragment_shader 						= gl.isExtensionAvailable("GL_ARB_fragment_shader");
		this.GL_ARB_framebuffer_no_attachments 				= gl.isExtensionAvailable("GL_ARB_framebuffer_no_attachments");
		this.GL_ARB_framebuffer_object 						= gl.isExtensionAvailable("GL_ARB_framebuffer_object");
		this.GL_ARB_framebuffer_sRGB 						= gl.isExtensionAvailable("GL_ARB_framebuffer_sRGB");
		this.GL_ARB_geometry_shader4 						= gl.isExtensionAvailable("GL_ARB_geometry_shader4");
		this.GL_ARB_get_program_binary 						= gl.isExtensionAvailable("GL_ARB_get_program_binary");
		this.GL_ARB_gpu_shader5 							= gl.isExtensionAvailable("GL_ARB_gpu_shader5");
		this.GL_ARB_gpu_shader_fp64 						= gl.isExtensionAvailable("GL_ARB_gpu_shader_fp64");
		this.GL_ARB_half_float_pixel 						= gl.isExtensionAvailable("GL_ARB_half_float_pixel");
		this.GL_ARB_half_float_vertex 						= gl.isExtensionAvailable("GL_ARB_half_float_vertex");
		this.GL_ARB_imaging 								= gl.isExtensionAvailable("GL_ARB_imaging");
		this.GL_ARB_instanced_arrays 						= gl.isExtensionAvailable("GL_ARB_instanced_arrays");
		this.GL_ARB_internalformat_query 					= gl.isExtensionAvailable("GL_ARB_internalformat_query");
		this.GL_ARB_internalformat_query2 					= gl.isExtensionAvailable("GL_ARB_internalformat_query2");
		this.GL_ARB_invalidate_subdata 						= gl.isExtensionAvailable("GL_ARB_invalidate_subdata");
		this.GL_ARB_map_buffer_alignment 					= gl.isExtensionAvailable("GL_ARB_map_buffer_alignment");
		this.GL_ARB_map_buffer_range 						= gl.isExtensionAvailable("GL_ARB_map_buffer_range");
		this.GL_ARB_matrix_palette 							= gl.isExtensionAvailable("GL_ARB_matrix_palette");
		this.GL_ARB_multi_draw_indirect 					= gl.isExtensionAvailable("GL_ARB_multi_draw_indirect");
		this.GL_ARB_multisample 							= gl.isExtensionAvailable("GL_ARB_multisample");
		this.GL_ARB_multitexture 							= gl.isExtensionAvailable("GL_ARB_multitexture");
		this.GL_ARB_occlusion_query 						= gl.isExtensionAvailable("GL_ARB_occlusion_query");
		this.GL_ARB_occlusion_query2 						= gl.isExtensionAvailable("GL_ARB_occlusion_query2");
		this.GL_ARB_pixel_buffer_object 					= gl.isExtensionAvailable("GL_ARB_pixel_buffer_object");
		this.GL_ARB_point_parameters 						= gl.isExtensionAvailable("GL_ARB_point_parameters");
		this.GL_ARB_point_sprite 							= gl.isExtensionAvailable("GL_ARB_point_sprite");
		this.GL_ARB_program_interface_query 				= gl.isExtensionAvailable("GL_ARB_program_interface_query");
		this.GL_ARB_provoking_vertex 						= gl.isExtensionAvailable("GL_ARB_provoking_vertex");
		this.GL_ARB_robust_buffer_access_behavior 			= gl.isExtensionAvailable("GL_ARB_robust_buffer_access_behavior");
		this.GL_ARB_robustness 								= gl.isExtensionAvailable("GL_ARB_robustness");
		this.GL_ARB_robustness_isolation 					= gl.isExtensionAvailable("GL_ARB_robustness_isolation");
		this.GL_ARB_sample_shading 							= gl.isExtensionAvailable("GL_ARB_sample_shading");
		this.GL_ARB_sampler_objects 						= gl.isExtensionAvailable("GL_ARB_sampler_objects");
		this.GL_ARB_seamless_cube_map 						= gl.isExtensionAvailable("GL_ARB_seamless_cube_map");
		this.GL_ARB_separate_shader_objects 				= gl.isExtensionAvailable("GL_ARB_separate_shader_objects");
		this.GL_ARB_shader_atomic_counters 					= gl.isExtensionAvailable("GL_ARB_shader_atomic_counters");
		this.GL_ARB_shader_bit_encoding 					= gl.isExtensionAvailable("GL_ARB_shader_bit_encoding");
		this.GL_ARB_shader_image_load_store 				= gl.isExtensionAvailable("GL_ARB_shader_image_load_store");
		this.GL_ARB_shader_image_size 						= gl.isExtensionAvailable("GL_ARB_shader_image_size");
		this.GL_ARB_shader_objects 							= gl.isExtensionAvailable("GL_ARB_shader_objects");
		this.GL_ARB_shader_precision 						= gl.isExtensionAvailable("GL_ARB_shader_precision");
		this.GL_ARB_shader_stencil_export 					= gl.isExtensionAvailable("GL_ARB_shader_stencil_export");
		this.GL_ARB_shader_storage_buffer_object 			= gl.isExtensionAvailable("GL_ARB_shader_storage_buffer_object");
		this.GL_ARB_shader_subroutine 						= gl.isExtensionAvailable("GL_ARB_shader_subroutine");
		this.GL_ARB_shader_texture_lod 						= gl.isExtensionAvailable("GL_ARB_shader_texture_lod");
		this.GL_ARB_shading_language_100 					= gl.isExtensionAvailable("GL_ARB_shading_language_100");
		this.GL_ARB_shading_language_420pack 				= gl.isExtensionAvailable("GL_ARB_shading_language_420pack");
		this.GL_ARB_shading_language_include 				= gl.isExtensionAvailable("GL_ARB_shading_language_include");
		this.GL_ARB_shading_language_packing 				= gl.isExtensionAvailable("GL_ARB_shading_language_packing");
		this.GL_ARB_shadow 									= gl.isExtensionAvailable("GL_ARB_shadow");
		this.GL_ARB_shadow_ambient 							= gl.isExtensionAvailable("GL_ARB_shadow_ambient");
		this.GL_ARB_stencil_texturing 						= gl.isExtensionAvailable("GL_ARB_stencil_texturing");
		this.GL_ARB_sync 									= gl.isExtensionAvailable("GL_ARB_sync");
		this.GL_ARB_tessellation_shader 					= gl.isExtensionAvailable("GL_ARB_tessellation_shader");
		this.GL_ARB_texture_border_clamp 					= gl.isExtensionAvailable("GL_ARB_texture_border_clamp");
		this.GL_ARB_texture_buffer_object 					= gl.isExtensionAvailable("GL_ARB_texture_buffer_object");
		this.GL_ARB_texture_buffer_object_rgb32 			= gl.isExtensionAvailable("GL_ARB_texture_buffer_object_rgb32");
		this.GL_ARB_texture_buffer_range 					= gl.isExtensionAvailable("GL_ARB_texture_buffer_range");
		this.GL_ARB_texture_compression 					= gl.isExtensionAvailable("GL_ARB_texture_compression");
		this.GL_ARB_texture_compression_bptc 				= gl.isExtensionAvailable("GL_ARB_texture_compression_bptc");
		this.GL_ARB_texture_compression_rgtc 				= gl.isExtensionAvailable("GL_ARB_texture_compression_rgtc");
		this.GL_ARB_texture_cube_map 						= gl.isExtensionAvailable("GL_ARB_texture_cube_map");
		this.GL_ARB_texture_cube_map_array 					= gl.isExtensionAvailable("GL_ARB_texture_cube_map_array");
		this.GL_ARB_texture_env_add 						= gl.isExtensionAvailable("GL_ARB_texture_env_add");
		this.GL_ARB_texture_env_combine 					= gl.isExtensionAvailable("GL_ARB_texture_env_combine");
		this.GL_ARB_texture_env_crossbar 					= gl.isExtensionAvailable("GL_ARB_texture_env_crossbar");
		this.GL_ARB_texture_env_dot3 						= gl.isExtensionAvailable("GL_ARB_texture_env_dot3");
		this.GL_ARB_texture_float 							= gl.isExtensionAvailable("GL_ARB_texture_float");
		this.GL_ARB_texture_gather 							= gl.isExtensionAvailable("GL_ARB_texture_gather");
		this.GL_ARB_texture_mirrored_repeat 				= gl.isExtensionAvailable("GL_ARB_texture_mirrored_repeat");
		this.GL_ARB_texture_multisample 					= gl.isExtensionAvailable("GL_ARB_texture_multisample");
		this.GL_ARB_texture_non_power_of_two 				= gl.isExtensionAvailable("GL_ARB_texture_non_power_of_two");
		this.GL_ARB_texture_query_levels 					= gl.isExtensionAvailable("GL_ARB_texture_query_levels");
		this.GL_ARB_texture_query_lod 						= gl.isExtensionAvailable("GL_ARB_texture_query_lod");
		this.GL_ARB_texture_rectangle 						= gl.isExtensionAvailable("GL_ARB_texture_rectangle");
		this.GL_ARB_texture_rg 								= gl.isExtensionAvailable("GL_ARB_texture_rg");
		this.GL_ARB_texture_rgb10_a2ui 						= gl.isExtensionAvailable("GL_ARB_texture_rgb10_a2ui");
		this.GL_ARB_texture_storage 						= gl.isExtensionAvailable("GL_ARB_texture_storage");
		this.GL_ARB_texture_storage_multisample 			= gl.isExtensionAvailable("GL_ARB_texture_storage_multisample");
		this.GL_ARB_texture_swizzle 						= gl.isExtensionAvailable("GL_ARB_texture_swizzle");
		this.GL_ARB_texture_view 							= gl.isExtensionAvailable("GL_ARB_texture_view");
		this.GL_ARB_timer_query 							= gl.isExtensionAvailable("GL_ARB_timer_query");
		this.GL_ARB_transform_feedback2 					= gl.isExtensionAvailable("GL_ARB_transform_feedback2");
		this.GL_ARB_transform_feedback3 					= gl.isExtensionAvailable("GL_ARB_transform_feedback3");
		this.GL_ARB_transform_feedback_instanced 			= gl.isExtensionAvailable("GL_ARB_transform_feedback_instanced");
		this.GL_ARB_transpose_matrix 						= gl.isExtensionAvailable("GL_ARB_transpose_matrix");
		this.GL_ARB_uniform_buffer_object 					= gl.isExtensionAvailable("GL_ARB_uniform_buffer_object");
		this.GL_ARB_vertex_array_bgra 						= gl.isExtensionAvailable("GL_ARB_vertex_array_bgra");
		this.GL_ARB_vertex_array_object 					= gl.isExtensionAvailable("GL_ARB_vertex_array_object");
		this.GL_ARB_vertex_attrib_64bit 					= gl.isExtensionAvailable("GL_ARB_vertex_attrib_64bit");
		this.GL_ARB_vertex_attrib_binding 					= gl.isExtensionAvailable("GL_ARB_vertex_attrib_binding");
		this.GL_ARB_vertex_blend 							= gl.isExtensionAvailable("GL_ARB_vertex_blend");
		this.GL_ARB_vertex_buffer_object 					= gl.isExtensionAvailable("GL_ARB_vertex_buffer_object");
		this.GL_ARB_vertex_program 							= gl.isExtensionAvailable("GL_ARB_vertex_program");
		this.GL_ARB_vertex_shader 							= gl.isExtensionAvailable("GL_ARB_vertex_shader");
		this.GL_ARB_vertex_type_2_10_10_10_rev 				= gl.isExtensionAvailable("GL_ARB_vertex_type_2_10_10_10_rev");
		this.GL_ARB_viewport_array 							= gl.isExtensionAvailable("GL_ARB_viewport_array");
		this.GL_ARB_window_pos 								= gl.isExtensionAvailable("GL_ARB_window_pos");
		this.GL_ATI_draw_buffers 							= gl.isExtensionAvailable("GL_ATI_draw_buffers");
		this.GL_ATI_element_array 							= gl.isExtensionAvailable("GL_ATI_element_array");
		this.GL_ATI_envmap_bumpmap 							= gl.isExtensionAvailable("GL_ATI_envmap_bumpmap");
		this.GL_ATI_fragment_shader 						= gl.isExtensionAvailable("GL_ATI_fragment_shader");
		this.GL_ATI_map_object_buffer 						= gl.isExtensionAvailable("GL_ATI_map_object_buffer");
		this.GL_ATI_meminfo 								= gl.isExtensionAvailable("GL_ATI_meminfo");
		this.GL_ATI_pn_triangles 							= gl.isExtensionAvailable("GL_ATI_pn_triangles");
		this.GL_ATI_separate_stencil 						= gl.isExtensionAvailable("GL_ATI_separate_stencil");
		this.GL_ATI_shader_texture_lod 						= gl.isExtensionAvailable("GL_ATI_shader_texture_lod");
		this.GL_ATI_text_fragment_shader 					= gl.isExtensionAvailable("GL_ATI_text_fragment_shader");
		this.GL_ATI_texture_compression_3dc 				= gl.isExtensionAvailable("GL_ATI_texture_compression_3dc");
		this.GL_ATI_texture_env_combine3 					= gl.isExtensionAvailable("GL_ATI_texture_env_combine3");
		this.GL_ATI_texture_float 							= gl.isExtensionAvailable("GL_ATI_texture_float");
		this.GL_ATI_texture_mirror_once 					= gl.isExtensionAvailable("GL_ATI_texture_mirror_once");
		this.GL_ATI_vertex_array_object 					= gl.isExtensionAvailable("GL_ATI_vertex_array_object");
		this.GL_ATI_vertex_attrib_array_object 				= gl.isExtensionAvailable("GL_ATI_vertex_attrib_array_object");
		this.GL_ATI_vertex_streams 							= gl.isExtensionAvailable("GL_ATI_vertex_streams");
		this.GL_EXT_abgr 									= gl.isExtensionAvailable("GL_EXT_abgr");
		this.GL_EXT_bgra 									= gl.isExtensionAvailable("GL_EXT_bgra");
		this.GL_EXT_bindable_uniform 						= gl.isExtensionAvailable("GL_EXT_bindable_uniform");
		this.GL_EXT_blend_color 							= gl.isExtensionAvailable("GL_EXT_blend_color");
		this.GL_EXT_blend_equation_separate 				= gl.isExtensionAvailable("GL_EXT_blend_equation_separate");
		this.GL_EXT_blend_func_separate 					= gl.isExtensionAvailable("GL_EXT_blend_func_separate");
		this.GL_EXT_blend_minmax 							= gl.isExtensionAvailable("GL_EXT_blend_minmax");
		this.GL_EXT_blend_subtract 							= gl.isExtensionAvailable("GL_EXT_blend_subtract");
		this.GL_EXT_Cg_shader 								= gl.isExtensionAvailable("GL_EXT_Cg_shader");
		this.GL_EXT_compiled_vertex_array 					= gl.isExtensionAvailable("GL_EXT_compiled_vertex_array");
		this.GL_EXT_depth_bounds_test 						= gl.isExtensionAvailable("GL_EXT_depth_bounds_test");
		this.GL_EXT_direct_state_access 					= gl.isExtensionAvailable("GL_EXT_direct_state_access");
		this.GL_EXT_draw_buffers2 							= gl.isExtensionAvailable("GL_EXT_draw_buffers2");
		this.GL_EXT_draw_instanced 							= gl.isExtensionAvailable("GL_EXT_draw_instanced");
		this.GL_EXT_draw_range_elements 					= gl.isExtensionAvailable("GL_EXT_draw_range_elements");
		this.GL_EXT_fog_coord 								= gl.isExtensionAvailable("GL_EXT_fog_coord");
		this.GL_EXT_framebuffer_blit 						= gl.isExtensionAvailable("GL_EXT_framebuffer_blit");
		this.GL_EXT_framebuffer_multisample 				= gl.isExtensionAvailable("GL_EXT_framebuffer_multisample");
		this.GL_EXT_framebuffer_multisample_blit_scaled 	= gl.isExtensionAvailable("GL_EXT_framebuffer_multisample_blit_scaled");
		this.GL_EXT_framebuffer_object 						= gl.isExtensionAvailable("GL_EXT_framebuffer_object");
		this.GL_EXT_framebuffer_sRGB 						= gl.isExtensionAvailable("GL_EXT_framebuffer_sRGB");
		this.GL_EXT_geometry_shader4 						= gl.isExtensionAvailable("GL_EXT_geometry_shader4");
		this.GL_EXT_gpu_program_parameters 					= gl.isExtensionAvailable("GL_EXT_gpu_program_parameters");
		this.GL_EXT_gpu_shader4 							= gl.isExtensionAvailable("GL_EXT_gpu_shader4");
		this.GL_EXT_multi_draw_arrays 						= gl.isExtensionAvailable("GL_EXT_multi_draw_arrays");
		this.GL_EXT_packed_depth_stencil 					= gl.isExtensionAvailable("GL_EXT_packed_depth_stencil");
		this.GL_EXT_packed_float 							= gl.isExtensionAvailable("GL_EXT_packed_float");
		this.GL_EXT_packed_pixels 							= gl.isExtensionAvailable("GL_EXT_packed_pixels");
		this.GL_EXT_paletted_texture 						= gl.isExtensionAvailable("GL_EXT_paletted_texture");
		this.GL_EXT_pixel_buffer_object 					= gl.isExtensionAvailable("GL_EXT_pixel_buffer_object");
		this.GL_EXT_point_parameters 						= gl.isExtensionAvailable("GL_EXT_point_parameters");
		this.GL_EXT_provoking_vertex 						= gl.isExtensionAvailable("GL_EXT_provoking_vertex");
		this.GL_EXT_rescale_normal 							= gl.isExtensionAvailable("GL_EXT_rescale_normal");
		this.GL_EXT_secondary_color 						= gl.isExtensionAvailable("GL_EXT_secondary_color");
		this.GL_EXT_separate_shader_objects 				= gl.isExtensionAvailable("GL_EXT_separate_shader_objects");
		this.GL_EXT_separate_specular_color 				= gl.isExtensionAvailable("GL_EXT_separate_specular_color");
		this.GL_EXT_shader_image_load_store 				= gl.isExtensionAvailable("GL_EXT_shader_image_load_store");
		this.GL_EXT_shadow_funcs 							= gl.isExtensionAvailable("GL_EXT_shadow_funcs");
		this.GL_EXT_shared_texture_palette 					= gl.isExtensionAvailable("GL_EXT_shared_texture_palette");
		this.GL_EXT_stencil_clear_tag 						= gl.isExtensionAvailable("GL_EXT_stencil_clear_tag");
		this.GL_EXT_stencil_two_side 						= gl.isExtensionAvailable("GL_EXT_stencil_two_side");
		this.GL_EXT_stencil_wrap 							= gl.isExtensionAvailable("GL_EXT_stencil_wrap");
		this.GL_EXT_texture_3d 								= gl.isExtensionAvailable("GL_EXT_texture_3d");
		this.GL_EXT_texture_array 							= gl.isExtensionAvailable("GL_EXT_texture_array");
		this.GL_EXT_texture_buffer_object 					= gl.isExtensionAvailable("GL_EXT_texture_buffer_object");
		this.GL_EXT_texture_compression_latc 				= gl.isExtensionAvailable("GL_EXT_texture_compression_latc");
		this.GL_EXT_texture_compression_rgtc 				= gl.isExtensionAvailable("GL_EXT_texture_compression_rgtc");
		this.GL_EXT_texture_compression_s3tc 				= gl.isExtensionAvailable("GL_EXT_texture_compression_s3tc");
		this.GL_EXT_texture_env_combine 					= gl.isExtensionAvailable("GL_EXT_texture_env_combine");
		this.GL_EXT_texture_env_dot3 						= gl.isExtensionAvailable("GL_EXT_texture_env_dot3");
		this.GL_EXT_texture_edge_clamp 						= gl.isExtensionAvailable("GL_EXT_texture_edge_clamp");
		this.GL_EXT_texture_filter_anisotropic 				= gl.isExtensionAvailable("GL_EXT_texture_filter_anisotropic");
		this.GL_EXT_texture_integer 						= gl.isExtensionAvailable("GL_EXT_texture_integer");
		this.GL_EXT_texture_lod_bias 						= gl.isExtensionAvailable("GL_EXT_texture_lod_bias");
		this.GL_EXT_texture_mirror_clamp 					= gl.isExtensionAvailable("GL_EXT_texture_mirror_clamp");
		this.GL_EXT_texture_rectangle 						= gl.isExtensionAvailable("GL_EXT_texture_rectangle");
		this.GL_EXT_texture_sRGB 							= gl.isExtensionAvailable("GL_EXT_texture_sRGB");
		this.GL_EXT_texture_sRGB_decode 					= gl.isExtensionAvailable("GL_EXT_texture_sRGB_decode");
		this.GL_EXT_texture_shared_exponent 				= gl.isExtensionAvailable("GL_EXT_texture_shared_exponent");
		this.GL_EXT_texture_snorm 							= gl.isExtensionAvailable("GL_EXT_texture_snorm");
		this.GL_EXT_texture_swizzle 						= gl.isExtensionAvailable("GL_EXT_texture_swizzle");
		this.GL_EXT_timer_query 							= gl.isExtensionAvailable("GL_EXT_timer_query");
		this.GL_EXT_transform_feedback 						= gl.isExtensionAvailable("GL_EXT_transform_feedback");
		this.GL_EXT_vertex_array_bgra 						= gl.isExtensionAvailable("GL_EXT_vertex_array_bgra");
		this.GL_EXT_vertex_attrib_64bit 					= gl.isExtensionAvailable("GL_EXT_vertex_attrib_64bit");
		this.GL_EXT_vertex_shader 							= gl.isExtensionAvailable("GL_EXT_vertex_shader");
		this.GL_EXT_vertex_weighting 						= gl.isExtensionAvailable("GL_EXT_vertex_weighting");
		this.GL_GREMEDY_string_marker 						= gl.isExtensionAvailable("GL_GREMEDY_string_marker");
		this.GL_HP_occlusion_test 							= gl.isExtensionAvailable("GL_HP_occlusion_test");
		this.GL_IBM_rasterpos_clip 							= gl.isExtensionAvailable("GL_IBM_rasterpos_clip");
		this.GL_INTEL_map_texture 							= gl.isExtensionAvailable("GL_INTEL_map_texture");
		this.GL_KHR_debug 									= gl.isExtensionAvailable("GL_KHR_debug");
		this.GL_KHR_texture_compression_astc_ldr 			= gl.isExtensionAvailable("GL_KHR_texture_compression_astc_ldr");
		this.GL_NVX_gpu_memory_info 						= gl.isExtensionAvailable("GL_NVX_gpu_memory_info");
		this.GL_NV_bindless_texture 						= gl.isExtensionAvailable("GL_NV_bindless_texture");
		this.GL_NV_blend_square 							= gl.isExtensionAvailable("GL_NV_blend_square");
		this.GL_NV_compute_program5 						= gl.isExtensionAvailable("GL_NV_compute_program5");
		this.GL_NV_conditional_render 						= gl.isExtensionAvailable("GL_NV_conditional_render");
		this.GL_NV_copy_depth_to_color 						= gl.isExtensionAvailable("GL_NV_copy_depth_to_color");
		this.GL_NV_copy_image 								= gl.isExtensionAvailable("GL_NV_copy_image");
		this.GL_NV_deep_texture3D 							= gl.isExtensionAvailable("GL_NV_deep_texture3D");
		this.GL_NV_depth_buffer_float 						= gl.isExtensionAvailable("GL_NV_depth_buffer_float");
		this.GL_NV_depth_clamp 								= gl.isExtensionAvailable("GL_NV_depth_clamp");
		this.GL_NV_draw_texture 							= gl.isExtensionAvailable("GL_NV_draw_texture");
		this.GL_NV_evaluators 								= gl.isExtensionAvailable("GL_NV_evaluators");
		this.GL_NV_explicit_multisample 					= gl.isExtensionAvailable("GL_NV_explicit_multisample");
		this.GL_NV_fence 									= gl.isExtensionAvailable("GL_NV_fence");
		this.GL_NV_float_buffer 							= gl.isExtensionAvailable("GL_NV_float_buffer");
		this.GL_NV_fog_distance 							= gl.isExtensionAvailable("GL_NV_fog_distance");
		this.GL_NV_fragment_program 						= gl.isExtensionAvailable("GL_NV_fragment_program");
		this.GL_NV_fragment_program2 						= gl.isExtensionAvailable("GL_NV_fragment_program2");
		this.GL_NV_fragment_program4 						= gl.isExtensionAvailable("GL_NV_fragment_program4");
		this.GL_NV_fragment_program_option 					= gl.isExtensionAvailable("GL_NV_fragment_program_option");
		this.GL_NV_framebuffer_multisample_coverage 		= gl.isExtensionAvailable("GL_NV_framebuffer_multisample_coverage");
		this.GL_NV_geometry_program4 						= gl.isExtensionAvailable("GL_NV_geometry_program4");
		this.GL_NV_geometry_shader4 						= gl.isExtensionAvailable("GL_NV_geometry_shader4");
		this.GL_NV_gpu_program4 							= gl.isExtensionAvailable("GL_NV_gpu_program4");
		this.GL_NV_gpu_program5 							= gl.isExtensionAvailable("GL_NV_gpu_program5");
		this.GL_NV_gpu_shader5 								= gl.isExtensionAvailable("GL_NV_gpu_shader5");
		this.GL_NV_half_float 								= gl.isExtensionAvailable("GL_NV_half_float");
		this.GL_NV_light_max_exponent 						= gl.isExtensionAvailable("GL_NV_light_max_exponent");
		this.GL_NV_multisample_coverage 					= gl.isExtensionAvailable("GL_NV_multisample_coverage");
		this.GL_NV_multisample_filter_hint 					= gl.isExtensionAvailable("GL_NV_multisample_filter_hint");
		this.GL_NV_occlusion_query 							= gl.isExtensionAvailable("GL_NV_occlusion_query");
		this.GL_NV_packed_depth_stencil 					= gl.isExtensionAvailable("GL_NV_packed_depth_stencil");
		this.GL_NV_parameter_buffer_object 					= gl.isExtensionAvailable("GL_NV_parameter_buffer_object");
		this.GL_NV_parameter_buffer_object2 				= gl.isExtensionAvailable("GL_NV_parameter_buffer_object2");
		this.GL_NV_path_rendering 							= gl.isExtensionAvailable("GL_NV_path_rendering");
		this.GL_NV_pixel_data_range 						= gl.isExtensionAvailable("GL_NV_pixel_data_range");
		this.GL_NV_point_sprite 							= gl.isExtensionAvailable("GL_NV_point_sprite");
		this.GL_NV_present_video 							= gl.isExtensionAvailable("GL_NV_present_video");
		this.GL_NV_primitive_restart 						= gl.isExtensionAvailable("GL_NV_primitive_restart");
		this.GL_NV_register_combiners 						= gl.isExtensionAvailable("GL_NV_register_combiners");
		this.GL_NV_register_combiners2 						= gl.isExtensionAvailable("GL_NV_register_combiners2");
		this.GL_NV_shader_atomic_counters 					= gl.isExtensionAvailable("GL_NV_shader_atomic_counters");
		this.GL_NV_shader_atomic_float 						= gl.isExtensionAvailable("GL_NV_shader_atomic_float");
		this.GL_NV_shader_buffer_load 						= gl.isExtensionAvailable("GL_NV_shader_buffer_load");
		this.GL_NV_shader_buffer_store 						= gl.isExtensionAvailable("GL_NV_shader_buffer_store");
		this.GL_NV_shader_storage_buffer_object 			= gl.isExtensionAvailable("GL_NV_shader_storage_buffer_object");
		this.GL_NV_tessellation_program5 					= gl.isExtensionAvailable("GL_NV_tessellation_program5");
		this.GL_NV_texgen_reflection 						= gl.isExtensionAvailable("GL_NV_texgen_reflection");
		this.GL_NV_texture_barrier 							= gl.isExtensionAvailable("GL_NV_texture_barrier");
		this.GL_NV_texture_compression_vtc 					= gl.isExtensionAvailable("GL_NV_texture_compression_vtc");
		this.GL_NV_texture_env_combine4 					= gl.isExtensionAvailable("GL_NV_texture_env_combine4");
		this.GL_NV_texture_expand_normal 					= gl.isExtensionAvailable("GL_NV_texture_expand_normal");
		this.GL_NV_texture_multisample 						= gl.isExtensionAvailable("GL_NV_texture_multisample");
		this.GL_NV_texture_rectangle 						= gl.isExtensionAvailable("GL_NV_texture_rectangle");
		this.GL_NV_texture_shader 							= gl.isExtensionAvailable("GL_NV_texture_shader");
		this.GL_NV_texture_shader2 							= gl.isExtensionAvailable("GL_NV_texture_shader2");
		this.GL_NV_texture_shader3 							= gl.isExtensionAvailable("GL_NV_texture_shader3");
		this.GL_NV_transform_feedback 						= gl.isExtensionAvailable("GL_NV_transform_feedback");
		this.GL_NV_transform_feedback2 						= gl.isExtensionAvailable("GL_NV_transform_feedback2");
		this.GL_NV_vertex_array_range 						= gl.isExtensionAvailable("GL_NV_vertex_array_range");
		this.GL_NV_vertex_array_range2 						= gl.isExtensionAvailable("GL_NV_vertex_array_range2");
		this.GL_NV_vertex_attrib_integer_64bit 				= gl.isExtensionAvailable("GL_NV_vertex_attrib_integer_64bit");
		this.GL_NV_vertex_buffer_unified_memory 			= gl.isExtensionAvailable("GL_NV_vertex_buffer_unified_memory");
		this.GL_NV_vertex_program 							= gl.isExtensionAvailable("GL_NV_vertex_program");
		this.GL_NV_vertex_program1_1 						= gl.isExtensionAvailable("GL_NV_vertex_program1_1");
		this.GL_NV_vertex_program2 							= gl.isExtensionAvailable("GL_NV_vertex_program2");
		this.GL_NV_vertex_program2_option 					= gl.isExtensionAvailable("GL_NV_vertex_program2_option");
		this.GL_NV_vertex_program3 							= gl.isExtensionAvailable("GL_NV_vertex_program3");
		this.GL_NV_vertex_program4 							= gl.isExtensionAvailable("GL_NV_vertex_program4");
		this.GL_NV_video_capture 							= gl.isExtensionAvailable("GL_NV_video_capture");
		this.GL_SGIS_generate_mipmap 						= gl.isExtensionAvailable("GL_SGIS_generate_mipmap");
		this.GL_SGIS_texture_lod 							= gl.isExtensionAvailable("GL_SGIS_texture_lod");
		this.GL_SUN_slice_accum 							= gl.isExtensionAvailable("GL_SUN_slice_accum");
	}
}
